#import "@local/mindtape:0.2.0": *

#show: task.with(
  title: "Cap a file by bytes as well as lines",
  status: proposed(2026, 10, 3),
)

= Summary

A line limit does not bound a file whose lines are paragraphs. Markdown
generated by typlite writes one line per paragraph, so a paragraph that grows
into an essay adds bytes and no lines.

Reported from mindtape, whose agents load `CONTRIBUTING.md` whole on every
session. Its override is `limit: 142`, and a 30 KB version of the file, cut
since, passes it:

```
$ git show c1a0bfb6:CONTRIBUTING.md | wc -lc
  128 30853
$ linecop --format paths   # that file restored, `./CONTRIBUTING.md` at `limit: 142`
$ echo $?
0
```

= Scope

- `max_bytes` on an override, beside `limit`. A file breaches when it exceeds
  either one, and the report names which: `--- CONTRIBUTING.md: 31204 bytes
  (max_bytes: 14000, +17204 over)`.
- `--baseline` applies to `max_bytes` as it does to `limit`.
- JSON output carries `bytes` and `max_bytes` for a file that has the key.
- An end-to-end test through the binary: a file under its line limit and over
  its byte limit fails the run.
- Schema, README, landing page and changelog name the new key.

= Out of scope

- A byte limit per language under `limits`. Lines measure code well, and the
  need is per file.
